languageCode = "en-us"
title = "Undervalued"
baseurl = "http://undervaluedblog.com/"
paginate = 5

[taxonomies]
	tag = "tags"
	category = "categories"

[[menu.main]]
    name = "Home"
    weight = -140
    identifier = "home"
    url = "/"
	
[[menu.main]]
    name = "About"
    weight = -130
    identifier = "about"
    url = "/about/"
	
[[menu.main]]
    name = "Disclaimer"
    weight = -120
    identifier = "disclaimer"
    url = "/disclaimer/"

[permalinks]
	post="/:year/:month/:title/"
	page="/:slug/"

[params]
	author = "me"
	# Show a sidebar menu
    showRightSidebar = true
    home = "undervalued"
	# BrandImage = "http://blog.appernetic.io/images/apperneticlogo.png" #top header brand image.
	BrandImage = ""


[params.theme]
  #name = "spacelab"
  # name = "slate"
  # name = "superhero"
  name = "yeti"
  
[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  
[Languages]
	[Languages.en]
	weight = 1
	copyright = "(c) 2017"
	title = "Undervalued"
