languageCode = "en-us"
title = "Undervalued"
baseurl = "http://undervaluedblog.com/"
copyright = "(C) 2017"
paginate = 5

[permalinks]
	post="/:year/:month/:title/"
	page="/:slug/"

[params]
	author = "me"
	
[params.sidebar]
	about = "A blog about programming and finance, but not financial programming."
	